import "dotenv/config";

import { interests } from "../schema/interests.schema";
import { profileInterests } from "../schema/profile-interests.schema";
import { db } from "../index";

const interestSeed = [
  { name: "Classical Music", category: "Music" },
  { name: "Traditional Music", category: "Music" },
  { name: "Old Songs", category: "Music" },
  { name: "Pop Music", category: "Music" },
  { name: "Rock Music", category: "Music" },
  { name: "Jazz Music", category: "Music" },
  { name: "Folk Music", category: "Music" },
  { name: "Electronic Music", category: "Music" },
  { name: "Bollywood Movies", category: "Movies" },
  { name: "Hollywood Movies", category: "Movies" },
  { name: "Comedy Movies", category: "Movies" },
  { name: "Action Movies", category: "Movies" },
  { name: "Romantic Movies", category: "Movies" },
  { name: "Thriller Movies", category: "Movies" },
  { name: "Documentary Movies", category: "Movies" },
  { name: "Animated Movies", category: "Movies" },
  { name: "Beach Trips", category: "Travel" },
  { name: "Mountain Trips", category: "Travel" },
  { name: "Road Trips", category: "Travel" },
  { name: "City Breaks", category: "Travel" },
  { name: "Backpacking", category: "Travel" },
  { name: "International Travel", category: "Travel" },
  { name: "Adventure Travel", category: "Travel" },
  { name: "Cultural Travel", category: "Travel" },
  { name: "Gym", category: "Fitness" },
  { name: "Running", category: "Fitness" },
  { name: "Yoga", category: "Fitness" },
  { name: "Swimming", category: "Fitness" },
  { name: "Cycling", category: "Fitness" },
  { name: "Meditation", category: "Fitness" },
  { name: "Strength Training", category: "Fitness" },
  { name: "Pilates", category: "Fitness" },
  { name: "Indian Food", category: "Food" },
  { name: "Street Food", category: "Food" },
  { name: "Desserts", category: "Food" },
  { name: "Italian Food", category: "Food" },
  { name: "Chinese Food", category: "Food" },
  { name: "Baking", category: "Food" },
  { name: "Coffee", category: "Food" },
  { name: "Healthy Eating", category: "Food" },
  { name: "Cricket", category: "Sports" },
  { name: "Football", category: "Sports" },
  { name: "Badminton", category: "Sports" },
  { name: "Basketball", category: "Sports" },
  { name: "Tennis", category: "Sports" },
  { name: "Volleyball", category: "Sports" },
  { name: "Table Tennis", category: "Sports" },
  { name: "Golf", category: "Sports" },
  { name: "Painting", category: "Creative" },
  { name: "Photography", category: "Creative" },
  { name: "Writing", category: "Creative" },
  { name: "Drawing", category: "Creative" },
  { name: "Crafts", category: "Creative" },
  { name: "Film Making", category: "Creative" },
  { name: "Graphic Design", category: "Creative" },
  { name: "Pottery", category: "Creative" },
  { name: "Dancing", category: "Dance" },
  { name: "Salsa Dancing", category: "Dance" },
  { name: "Classical Dancing", category: "Dance" },
  { name: "Hip Hop Dancing", category: "Dance" },
  { name: "Ballet", category: "Dance" },
  { name: "Contemporary Dance", category: "Dance" },
  { name: "Folk Dancing", category: "Dance" },
  { name: "Zumba", category: "Dance" },
  { name: "Fiction Books", category: "Reading" },
  { name: "Poetry", category: "Reading" },
  { name: "History Books", category: "Reading" },
  { name: "Mystery Books", category: "Reading" },
  { name: "Science Fiction Books", category: "Reading" },
  { name: "Biographies", category: "Reading" },
  { name: "Self-Help Books", category: "Reading" },
  { name: "News and Current Affairs", category: "Reading" },
  { name: "Video Games", category: "Gaming" },
  { name: "Board Games", category: "Gaming" },
  { name: "Chess", category: "Gaming" },
  { name: "Mobile Games", category: "Gaming" },
  { name: "Card Games", category: "Gaming" },
  { name: "Role-Playing Games", category: "Gaming" },
  { name: "Strategy Games", category: "Gaming" },
  { name: "Trivia Games", category: "Gaming" },
  { name: "Hiking", category: "Nature" },
  { name: "Camping", category: "Nature" },
  { name: "Wildlife", category: "Nature" },
  { name: "Gardening", category: "Nature" },
  { name: "Bird Watching", category: "Nature" },
  { name: "Nature Walks", category: "Nature" },
  { name: "Stargazing", category: "Nature" },
  { name: "Sustainable Living", category: "Nature" },
];

export const seedInterests = async () => {
  await db.delete(profileInterests);
  await db.delete(interests);

  await db.insert(interests).values(interestSeed);

  console.log(`Inserted ${interestSeed.length} interest records.`);
};
